# Unit test, full matrix

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux']
    python_versions: ['3.6', '3.5']
    tf_versions: ['1.12', '1.11']
    onnx_versions: ['1.3']
    onnx_opsets: ['7', '8']
    onnx_backends:
      onnxruntime: ['0.1.3', '0.1.4']
    job:
      steps:
      - template: 'unit_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['windows', 'mac']
    tf_versions: ['1.12']
    onnx_versions: ['1.3']
    onnx_backends:
      onnxruntime: ['0.1.3']
    job:
      steps:
      - template: 'unit_test.yml'
